### GET a password by name
GET http://localhost:3333/api/passwords/Steffen

### GET a unknown password by name
GET http://localhost:3333/api/passwords/nixxx

### DELETE a password by name
DELETE http://localhost:3333/api/passwords/wifi

### POST a new password 
POST http://localhost:3333/api/passwords
Content-Type: application/json

{
    "name": "wifi",
    "value": "sehr-sicher"
}
