### GET a password by name
GET http://localhost:3333/api/passwords/google


### DELETE a password by name
DELETE http://localhost:3333/api/passwords/google

### GET a unknown password by name
GET http://localhost:3333/api/passwords/nixxx


### POST a new password 
POST http://localhost:3333/api/passwords
Content-Type: application/json
{
"name": "WiFi",
"value": "ganz-ganz-sicher" 
}